project:
  title: "Dunciad Visualizations"
  type: website
  output-dir: docs

website:
  title: "Dunciad Visualizations"
  navbar:
    left:
      - href: index.qmd
        text: Graphs
      - href: MakeGraphs.ipynb
        text: Notebook

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    default-image-extension: svg